name: chat-django-prod

services:
  web:
    build: 
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn a_core.asgi:application -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000
    volumes:
      - static-data:/home/app/web/static
    env_file:
      - .env.prod
    depends_on:
      - db

  db:
    image: postgres:16
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env.prod
    environment:
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
      - POSTGRES_DB=${SQL_DATABASE}

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  nginx:
    build: ./nginx
    volumes:
      - static-data:/home/app/web/static
    ports:
      - 80:80
    depends_on:
      - web


volumes:
  postgres-data:
  static-data: